version: '3'

services:
  backend:
    image: 'cloudbackend:1.0'
    build: "./"
    ports:
      - "8081:8081"

  database:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql