version: '3.1'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql_data:/var/lib/sql/data
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'

  backend:
    image: cloudbackend:1.0
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - db
